name = "skogai01"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[[r2_buckets]]
binding = "skogaiR2bucket"
bucket_name = "skogai01"

[assets]
directory = "./public"
binding = "ASSETS"   # (används inte nu när UI är inline, men bra att ha för framtiden)
